# Generated by Django 3.1.1 on 2020-09-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_level',
            field=models.IntegerField(choices=[(1, 'Fundamental Awarness (basic knowledge)'), (2, 'Novice (limited experience)'), (3, 'Intermediate (practical application)'), (4, 'Advanced (applied theory)'), (5, 'Expert (recognized authority)')]),
        ),
    ]
