# Generated by Django 3.1.1 on 2020-09-14 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_image', models.ImageField(upload_to='')),
                ('cover_image1', models.ImageField(null=True, upload_to='')),
                ('cover_image2', models.ImageField(null=True, upload_to='')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('current_address1', models.CharField(max_length=100, null=True)),
                ('current_address2', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
